### ISSUE TITLE
Arduino_CAN library missing

### ISSUE THREAD

**Issue by rakesh5283** [arduino-libraries/Arduino_PortentaMachineControl#11]
With updated version .. Arduino_CAN.h is missing. 

Following error:

`c:\Users\DELL\Documents\Arduino\libraries\Arduino_PortentaMachineControl\src/CANCommClass.h:16:10: fatal error: Arduino_CAN.h: No such file or directory`
 
`#include <Arduino_CAN.h>`

**Comment by facchinm** [comment]
Hi @rakesh5283 , you need an updated version of the Portenta core to compile the latest version. Please recheck after updating the core to 4.1.1

**Comment by rakesh5283** [comment]
I am using Arduino PLC IDE and by default it download **arduino_mbed_portenta_3.5.4_6b52e2f35dd4808f** this folder.. do I have to set somewhere in the IDE to download the latest one.

**Comment by manchoz** [comment]
Hi,
You can't update the core this way (it simply won't work).
The Library entry is meant only to add extra libraries needed by the sketch (ArduinoMqttClient is ok).
You can't update the MachinControl library, too.

What are you trying to achieve?

**Comment by rakesh5283** [comment]
OK.. I understand core will not update using library so the next is how can i update the core 4.1.1 on Arduino PLC IDE

**Comment by manchoz** [comment]
Hi @rakesh5283,
Unfortunately, it is not possible for the user. You need to wait for the next version of the PLC IDE (in a few weeks).

Why do you need to update the core?

**Comment by rakesh5283** [comment]
Thank You for your message. 

I am trying to send my PLC result over wifi to my PC using MQTT or websocket protocol. 

So My PLC system works fine with my mechanical system and HMI which uses RS485, Analog Input, thermocouple inputs. Now I want to push those results data to my server using MQTT or Wesocket protocol. So I have integreated MQTT which simply push data to broker using Portenta Machine control wifi and its sample code which is integrated with my existing sketch code. and its stuck up complete system. 


So I checked if WiFiSimpleSender example code from ArduinoMQTTClient will work or not by simply copy paste that sketch to PLC IDE sketch editor and upload it to PLC, but also it does not work.. please see attached capture video. 

So the question is does PLC IDE will work with PLC ladder program and WIfi sketch program. 

Please find below capture video link : https://we.tl/t-u6vsYak14C

**Comment by manchoz** [comment]
I appreciate your clarifications.

The upcoming release will also include support for networking (WiFi or Ethernet) in PLC IDE.

If you have any other questions or issues regarding the PLC IDE, contact us at pro@arduino.cc.

**Comment by rakesh5283** [comment]
Thank You,

 May I know when the next release will be out. Any tentative date or month. 

Rakesh

**Comment by manchoz** [comment]
This month (April).

**Comment by rakesh5283** [comment]
Hi, @manchoz 

 Any update on Arduino PLC IDE release, as mentioned in this month (April).

Rakesh

**Comment by manchoz** [comment]
We will release in a few. Stay tuned.

**Comment by rakesh5283** [comment]
Days ?
